- name: Installs zsh | pacman
  become: true
  pacman:
    name: zsh
    state: present

- name: Sets zsh as default shell for my user | command
  become: true
  command: chsh -s /bin/zsh {{ lookup('env', 'USER') }}
  register: zsh_for_user
  failed_when: zsh_for_user.rc >= 1
  changed_when: zsh_for_user.rc == 0

- name: Checks for oh-my-zsh installation | stat
  stat:
    path: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"
  register: oh_my_zsh_stat

- name: Install oh-my-zsh | raw
  raw: 'sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
  when: not oh_my_zsh_stat

- name: Install powerlevel10k | git
  git:
    repo: https://github.com/romkatv/powerlevel10k
    dest: ${HOME}/.oh-my-zsh/custom/themes/powerlevel10k

- name: Install zsh-autosuggestions | git
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ${HOME}/.oh-my-zsh/plugins/zsh-autosuggestions

- name: Install zsh-syntax-highlighting | git
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting
    dest: ${HOME}/.oh-my-zsh/plugins/zsh-syntax-highlighting

- name: Install zsh-k | git
  git:
    repo: https://github.com/supercrabtree/k
    dest: ${HOME}/.oh-my-zsh/plugins/k

- name: Install autojump | shell
  shell: |
    cd ${HOME}/Downloads
    git clone https://github.com/Martinhinnerson/autojump.git
    cd autojump
    ./install.py