- name: Include vars
  include_vars: main.yml
  when: install_gaming

- name: Install gaming_pkgs | pacman
  tags:
    - packages
  become: true
  pacman:
    name: "{{ gaming_pkgs }}"
  when: install_gaming

- name: Enable gaming services | shell
  become: true
  shell: |
    systemctl --user enable gamemoded && systemctl --user start gamemoded
    systemctl enable --now earlyoom
    sudo sysctl -w net.core.netdev_max_backlog = 16384
    sudo sysctl -w net.core.somaxconn = 8192
    sudo sysctl -w net.core.rmem_default = 1048576
    sudo sysctl -w net.core.rmem_max = 16777216
    sudo sysctl -w net.core.wmem_default = 1048576
    sudo sysctl -w net.core.wmem_max = 16777216
    sudo sysctl -w net.core.optmem_max = 65536
    sudo sysctl -w net.ipv4.tcp_rmem = 4096 1048576 2097152
    sudo sysctl -w net.ipv4.tcp_wmem = 4096 65536 16777216
    sudo sysctl -w net.ipv4.udp_rmem_min = 8192
    sudo sysctl -w net.ipv4.udp_wmem_min = 8192
    sudo sysctl -w net.ipv4.tcp_fastopen = 3
    sudo sysctl -w net.ipv4.tcp_max_syn_backlog = 8192
    sudo sysctl -w net.ipv4.tcp_max_tw_buckets = 2000000
    sudo sysctl -w vm.swappiness = 10
  when: install_gaming