- name: Include vars
  include_vars: main.yml 

- name: Install Utilities | pacman
  become: true
  pacman:
    name: "{{ utils }}"

- name: Install Applications | pacman
  become: true
  pacman:
    name: "{{ applications }}"
