utils:
  - htop
  - iotop
  - ripgrep
  - rsync
  - strace
  - unzip
  - which
  - ffmpeg
  - libx11
  - lazygit
  - wget
  - stylua
applications:
  - chromium
  - gnome-terminal-transparency

gnome_terminal_font_size: 10
window_manager_font_size: 10
