- name: Install lightdm | pacman
  tags: lightdm
  become: true
  pacman:
    name:
      - lightdm
      - lightdm-webkit2-greeter
    state: present

- name: Install lightdm theme | shell
  tags: lightdm
  become: true
  shell: |
    cd $HOME/Downloads/
    wget git.io/webkit2 -O theme.tar.gz
    mkdir glorious
    mv theme.tar.gz glorious/
    cd glorious
    tar zxvf theme.tar.gz
    rm theme.tar.gz
    cd ..
    sudo rm -rf /usr/share/lightdm-webkit/themes/glorious
    sudo mv glorious/ /usr/share/lightdm-webkit/themes/

- name: Write lightdm greeter configuration | template
  tags: lightdm
  become: true
  template:
    src: lightdm/{{ lightdm_greeter_session }}.conf
    dest: /etc/lightdm
    owner: root
    group: root
    mode: 'u=rw,go=r'

- name: Write lightdm configuration | template
  tags: lightdm
  become: true
  template:
    src: lightdm/lightdm.conf
    dest: /etc/lightdm
    owner: root
    group: root
    mode: 'u=rw,go=r'

- name: Enable essential services | shell
  tags: lightdm
  become: true
  shell: |
    sudo systemctl enable lightdm
