- name: Include vars
  include_vars: main.yml

- name: Create scripts directory | file
  become: true
  file: 
    name: ${HOME}/bin
    state: directory
    group: users
    mode: 0755

- name: Create Downloads directory | file
  become: true
  file: 
    name: ${HOME}/Downloads
    state: directory
    group: users
    mode: 0755

- name: Create Templates directory | file
  become: true
  file: 
    name: ${HOME}/Templates
    state: directory
    group: users
    mode: 0755

- name: Create Public directory | file
  become: true
  file: 
    name: ${HOME}/Public
    state: directory
    group: users
    mode: 0755

- name: Create Downloads directory | file
  become: true
  file: 
    name: ${HOME}/Downloads
    state: directory
    group: users
    mode: 0755

- name: Create Music directory | file
  become: true
  file: 
    name: ${HOME}/Music
    state: directory
    group: users
    mode: 0755

- name: Create Pictures directory | file
  become: true
  file: 
    name: ${HOME}/Pictures
    state: directory
    group: users
    mode: 0755

- name: Create Videos directory | file
  become: true
  file: 
    name: ${HOME}/Videos
    state: directory
    group: users
    mode: 0755

- name: Add ansible community packages | raw
  raw: "ansible-galaxy collection install community.general"

- name: Install YAY | shell
  shell: |
    cd ~
    git clone "https://aur.archlinux.org/yay.git"
    cd ${HOME}/yay
    makepkg -si --noconfirm

- name: Install user_pkgs | pacman
  tags:
    - packages
  become: true
  pacman:
    name: "{{ user_pkgs }}"

- name: Install background | shell
  shell: |
    cp $HOME/ArchObscurely/background.jpg $HOME/Pictures/background.jpg
    sudo ln -s "$HOME/Pictures/background.jpg" /usr/share/backgrounds/background.jpg
  ignore_errors: true

- name: Create .local directory | file
  become: true
  file: 
    name: ${HOME}/.local
    state: directory
    group: users
    mode: 0755

- name: Create .local/share directory | file
  become: true
  file: 
    name: ${HOME}/.local/share
    state: directory
    group: users
    mode: 0755

- name: Create .local/share/fonts directory | file
  become: true
  file: 
    name: ${HOME}/.local/share/fonts
    state: directory
    group: users
    mode: 0755

- name: Clone PolybarRofiFonts | git
  git: 
    repo: https://github.com/Obscurely/PolybarRofiFonts.git 
    dest: ${HOME}/.local/share/fonts

- name: Scan new fonts | shell
  shell: |
    fc-cache
    sleep 3

- include: lightdm.yml
  when: install_lightdm | bool

- name: Enable essential services | shell
  become: true
  shell: |
    sudo ntpd -qg
    sudo systemctl enable ntpd.service
    sudo systemctl disable dhcpcd.service
    sudo systemctl stop dhcpcd.service
    sudo systemctl enable NetworkManager.service
    sudo systemctl enable libvirtd.service

- name: Add current user to libvirtd group | shell
  become: true
  shell: |
    sudo usermod -G libvirt -a $(whoami)

- name: Fix "too many files" error in vscode | shell
  become: true
  shell: |
    echo fs.inotify.max_user_watches=524288 | sudo tee /etc/sysctl.d/40-max-user-watches.conf && sudo sysctl --system

- name: Install Tig | shell
  become: true
  shell: |
    cd ${HOME}/Downloads
    git clone https://github.com/jonas/tig
    cd tig
    make configure
    ./configure
    make
    make install

- name: Setup UFW rules | shell
  become: true
  shell: |
    sudo ufw limit 22/tcp
    sudo ufw allow 80/tcp
    sudo ufw allow 443/tcp
    sudo ufw default deny incoming
    sudo ufw default allow outgoing
    sudo ufw enable

- name: Bootstrap dotfiles | shell
  shell: |
    {{ playbook_dir }}/../dotfiles/install.sh
  when: install_dotfiles | bool
