- name: Include vars
  include_vars: main.yml

- name: Install packages | pacman
  tags:
    - packages
  become: true
  pacman:
    name: "{{ i3_packages }}"
    state: "{{ i3_packages_state | default('present') }}"

- name: Sync i3 config | synchronize
  synchronize:
    src: templates/i3
    dest: ~/.config

- name: Set i3 terminal | blockinfile
  blockinfile:
    dest: ~/.config/i3/config
    insertafter: '^(.*)#ANSIBLE(.*)$'
    marker: "# {mark} ANSIBLE MANAGED BLOCK - TERMINAL"
    block: |
      # start a terminal
      bindsym $mod+Return exec alacritty
  
- name: Set dmenu as program launcher | blockinfile
  blockinfile:
    dest: ~/.config/i3/config
    insertafter: '^(.*)#ANSIBLE(.*)$'
    marker: "# {mark} ANSIBLE MANAGED BLOCK - PROGRAM LAUNCHER"
    block: |
      bindsym $mod+d exec --no-startup-id dmenu_run
  when: i3_program_launcher == "dmenu"

- name: Enable picom | blockinfile
  blockinfile:
    dest: ~/.config/i3/config
    insertafter: '^(.*)#ANSIBLE(.*)$'
    marker: "# {mark} ANSIBLE MANAGED BLOCK - PICOM"
    block: |
      # Run Picom at startup
      {{ enable_picom }}exec --no-startup-id picom --config ~/.config/picom.conf/picom.conf

- name: Enable nitrogen | blockinfile
  blockinfile:
    dest: ~/.config/i3/config
    insertbefore: '^(.*)#ANSIBLE(.*)$'
    marker: "# {mark} ANSIBLE MANAGED BLOCK - NITROGEN"
    block: |
      # Run Nitrogen at startup
      exec --no-startup-id nitrogen --restore

- name: Remove i3 border | blockinfile
  blockinfile:
    dest: ~/.config/i3/config
    insertbefore: '^(.*)#ANSIBLE(.*)$'
    marker: "# {mark} ANSIBLE MANAGED BLOCK - BORDER"
    block: |
      default_border pixel 1
      default_floating_border pixel 1

- name: Fetch wallpapers | git
  git:
    repo: "{{ i3_wallpaper }}"
    dest: ~/Pictures/i3_wallpapers
  when: install_wallpaper | bool

- name: Install background | shell
  shell: |
    cp $HOME/ArchObscurely/background.jpg $HOME/Pictures/background.jpg
    sudo ln -s "$HOME/Pictures/background.jpg" /usr/share/backgrounds/background.jpg
  ignore_errors: true

- include: polybar.yml
  when: install_polybar | bool

- include: rofi.yml
  when: i3_program_launcher == "rofi"

- include: i3lock.yml
  when: install_i3lock | bool
