- name: Install polybar | pacman
  become: true
  pacman:
    name: polybar
    state: present

- name: Sync polybar config | synchronize
  synchronize:
    src: templates/polybar
    dest: ~/.config
    
- name: Enable polybar in i3 | blockinfile
  blockinfile:
    dest: ~/.config/i3/config
    insertafter: '^(.*)#ANSIBLE(.*)$'
    marker: "# {mark} ANSIBLE MANAGED BLOCK POLYBAR"
    block: |
      exec --no-startup-id ~/.config/polybar/launch.sh
  
