- name: Set up local workstation
  hosts: local
  roles:
    - {role: base, tags: base}
    - {role: user, tags: user}
    - {role: gaming, tags: gaming}
    - {role: zsh, tags: zsh}
    - {role: python, tags: python}
    # - role: i3
    # - role: node
    # - role: rust
    # - role: lua
  vars_files:
    - vars/global.yml
