- name: Set up local workstation
  hosts: local
  roles:
    - {role: base, tags: base}
    - {role: user, tags: user}
    # - role: utils
    # - role: zsh
    # - role: i3
    # - role: python
    # - role: node
    # - role: rust
    # - role: lua
  vars_files:
    - vars/global.yml
